apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 31200
      targetPort: 80
  type: LoadBalancer

